import { Metadata } from "next";
import dynamic from "next/dynamic";
export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

//When client side code also runs on the server,
//It can cause dom problems
//To combat that we would use dynamic imports of client side code to prevent the
//code running on server ,and it should only run on the client
const LoginPartial = dynamic(() => import("@/components/LoginPartial"), {
  ssr: false,
});
const Login = () => {
  console.log("This is login page");
  return (
    <div className="h-[80vh] flex items-center justify-center w-full">
      <LoginPartial />
    </div>
  );
};

export default Login;
